apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: openshift-kubernetes-bot
  name: openshift-kubernetes-bot
  namespace: origin-publishing-bot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: openshift-kubernetes-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: openshift-kubernetes-bot
    spec:
      containers:
      - command:
        - /publishing-bot
        - --alsologtostderr
        - --config=/etc/munge-config/config
        - --rules-file=https://raw.githubusercontent.com/openshift/origin/master/publishing-kube-rules.yaml
        - --token-file=/etc/secret-volume/token
        - --interval=14400
        - --server-port=8080
        - 2>&1
        env:
        - name: FORCE_DEPLOY
          value: "1"
        image: docker.io/sttts/k8s-publishing-bot:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: publisher
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/munge-config
          name: munge-config
        - mountPath: /etc/secret-volume
          name: secret-volume
        - mountPath: /netrc
          name: netrc
        - mountPath: /gitrepos
          name: repo
        - mountPath: /go-workspace
          name: publisher-gopath
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /init-repo
        - --alsologtostderr
        - --config=/etc/munge-config/config
        - --rules-file=https://raw.githubusercontent.com/openshift/origin/master/publishing-kube-rules.yaml
        - 2>&1
        image: docker.io/sttts/k8s-publishing-bot:latest
        imagePullPolicy: Always
        name: initialize-repos
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/munge-config
          name: munge-config
        - mountPath: /go-workspace
          name: publisher-gopath
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: openshift-kubernetes-bot-config
        name: munge-config
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: github-token
      - emptyDir: {}
        name: repo
      - emptyDir:
          medium: Memory
        name: netrc
      - name: publisher-gopath
        persistentVolumeClaim:
          claimName: openshift-kubernetes-gopath
status:
